### ISSUE TITLE
Missing gcd_feature_type table in dump?

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-support#4]
Hi folks,
  I was thrilled to see the `gcd_feature` table in the data dump, but noticed it references a `gcd_feature_type` table that is missing.

  Is this still the right script for the dumps?  https://github.com/GrandComicsDatabase/gcd-support/blob/master/scripts/gcd-export.pl  I was going to open a PR but noticed that even `gcd_feature` isn't in that script so I got a little confused.

  I think `stddata_currency` might also be missing, but I'm a little unclear on where that gets used so maybe that's intentional.

**Comment by jochengcd** [comment]
gcd_feature_type and gcd_feature_relation_type are now added to the script on production, will update it in the support repo

stddata_currency is only used for my.comics.org, so doesn't need to be exported.

**Comment by jochengcd** [comment]
Forgot to add, a fresh data dump is just being generated.

**Comment by handrews** [comment]
Thanks, Jochen!  The currency thing reminds me of something else but I'll file it separately.
